[package]
name = "plotlars"
version = "0.10.0"
authors = ["Alberto Cebada Aleu <contact@albertocebada.com>"]
edition = "2021"
rust-version = "1.86.0"
description = "Plotlars is a Rust library designed to facilitate the integration between the Polars data analysis library and visualization libraries."
documentation = "https://docs.rs/plotlars/latest/plotlars/"
readme = "README.md"
homepage = "https://github.com/alceal/plotlars"
repository = "https://github.com/alceal/plotlars"
license = "MIT"
keywords = ["chart", "plot", "plotly", "polars", "visualization"]
categories = ["visualization"]

[dependencies]
ndarray = "0.16.1"
bon = "3.6.5"
image = "0.25.6"
indexmap = "2.10.0"
ordered-float = "5.0.0"
plotly = "0.13.5"
plotly_static = { version = "0.0.4", optional = true }
polars = { version = "0.50", default-features = false, features = ["dtype-slim", "lazy", "pivot", "docs", "zip_with", "fmt_no_tty", "dtype-categorical"] }
polars-io = { version = "0.50", default-features = false, features = ["csv"] }
serde = "1.0.219"
serde_json = "1.0.142"

[features]
static_export_chromedriver = ["plotly/static_export_chromedriver", "plotly_static"]
static_export_geckodriver = ["plotly/static_export_geckodriver", "plotly_static"]
static_export_wd_download = ["plotly/static_export_wd_download"]
static_export_default = ["plotly/static_export_default", "plotly_static"]

[dev-dependencies]
ndarray = "0.16.1"
